/*
    Offline Loader Component
    @Author: Grok
    @Date: 2023-06-01
    @Notes: This was generated by Grok Test Suite and modified by Christian Thompson
*/
import { useState, useEffect } from "react";
import Alert from "@mui/material/Alert";
import AlertTitle from "@mui/material/AlertTitle";
import Box from "@mui/material/Box";
import OfflineBoltIcon from "@mui/icons-material/OfflineBoltOutlined";
import { Typography } from "@mui/material";

const HEARTBEAT_URL = 'https://api.weather.gov/'; // Very reliable, no CORS issues on HEAD

export default function OfflineLoader({ skeletonLoader, time = 3000 }) {
  const [phase, setPhase] = useState('loading');

  // Real connectivity test
  const checkConnectivity = async () => {
    try {
      await fetch(HEARTBEAT_URL, {
        method: 'HEAD',
        mode: 'no-cors',
        cache: 'no-store',
      });
      return true;
    } catch (err) {
      return false;
    }
  };

  // Phase 1: Show skeleton for minimum time
  useEffect(() => {
    const timer = setTimeout(async () => {
      const isOnline = await checkConnectivity();
      setPhase(isOnline ? 'online' : 'offline');
    }, time);

    return () => clearTimeout(timer);
  }, [time]);

  // Phase 2: Continuously monitor real connectivity
  useEffect(() => {
    const handleConnectivityChange = async () => {
      if (phase === 'loading') return; // Don't interrupt grace period

      const isOnline = await checkConnectivity();
      setPhase(isOnline ? 'online' : 'offline');
    };

    window.addEventListener('online', handleConnectivityChange);
    window.addEventListener('offline', handleConnectivityChange);

    // Optional: periodic heartbeat every 10s
    const interval = setInterval(handleConnectivityChange, 10000);

    return () => {
      window.removeEventListener('online', handleConnectivityChange);
      window.removeEventListener('offline', handleConnectivityChange);
      clearInterval(interval);
    };
  }, [phase]);

  return (
    <Box
      id="offline-loader"
      sx={{
        width: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      {phase === "loading" && skeletonLoader}
      {phase === "offline" && (
        <Alert severity="warning" icon={<OfflineBoltIcon />}>
          <AlertTitle>You're offline</AlertTitle>
          <Typography variant="body2">
            Showing cached data. Reconnect to update.
          </Typography>
        </Alert>
      )}
    </Box>
  );
}
